<?php
/**
 * Blank File that's just here to get d.o. to build so we can hit the make file
 */

/**
 * Implements hook_menu().
 */
function ulmus_core_menu() {
  $items['ulmus/new-idea'] = array(
    'title' => t('A new idea'),
    'page callback' => '_ulmus_your_idea',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Callback for a description of what this is.
 * @return string
 */
function _ulmus_your_idea() {
  $output = '<p>' . t("") . '</p>';
  return $output;
}
